---
- name: ensure elasticsearch apt key is present.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: ensure elasticsearch repository is registred.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
    state: present
    update_cache: yes

- name: ensure elasticsearch is installed.
  apt:
    name: elasticsearch
    state: present

- name: ensure elasticsearch is listening on all interface.
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: 'network\.host', line: 'network.host: 0.0.0.0' }

  notify: ensure elasticsearch is restarted.

- name: ensure elasticsearch node has the valid cluster name & node name
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: 'cluster\.name:', line: 'cluster.name: {{ elasticsearch_cluster_name }}' }
    - { regexp: 'node\.name:', line: 'node.name: {{ elasticsearch_node_name }}' }
  notify: ensure elasticsearch is restarted.

- name: ensure elasticsearch has memory setting.
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '-Xms', line: '-Xms{{ elasticsearch_jvm_options_memory }}' }
    - { regexp: '-Xmx', line: '-Xmx{{ elasticsearch_jvm_options_memory }}' }
  notify: ensure elasticsearch is restarted.

- name: ensure elasticsearch is started
  service: name=elasticsearch state=started enabled=yes
