galaxy_info:
  author: fabien arcellier
  description: setup openjdk-8-jre on ubuntu
  company: your company (optional)

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  platforms:
  - name: Ubuntu
    versions:
      - precise
      - trusty
      - xenial

  galaxy_tags: []

dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
