galaxy_info:
  author: fabien arcellier
  description: setup openjdk-8-jre on ubuntu

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  platforms:
  - name: Ubuntu
    versions:
      - precise
      - trusty
      - xenial

  galaxy_tags: []

dependencies: []
